# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11rpc_message.proto\"\'\n\tRpcAddReq\x12\x0c\n\x04num1\x18\x01 \x01(\x03\x12\x0c\n\x04num2\x18\x02 \x01(\x03\"\x1b\n\tRpcAddRsp\x12\x0e\n\x06result\x18\x01 \x01(\x03\x62\x06proto3')
)




_RPCADDREQ = _descriptor.Descriptor(
  name='RpcAddReq',
  full_name='RpcAddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='RpcAddReq.num1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='RpcAddReq.num2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=60,
)


_RPCADDRSP = _descriptor.Descriptor(
  name='RpcAddRsp',
  full_name='RpcAddRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='RpcAddRsp.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['RpcAddReq'] = _RPCADDREQ
DESCRIPTOR.message_types_by_name['RpcAddRsp'] = _RPCADDRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcAddReq = _reflection.GeneratedProtocolMessageType('RpcAddReq', (_message.Message,), dict(
  DESCRIPTOR = _RPCADDREQ,
  __module__ = 'rpc_message_pb2'
  # @@protoc_insertion_point(class_scope:RpcAddReq)
  ))
_sym_db.RegisterMessage(RpcAddReq)

RpcAddRsp = _reflection.GeneratedProtocolMessageType('RpcAddRsp', (_message.Message,), dict(
  DESCRIPTOR = _RPCADDRSP,
  __module__ = 'rpc_message_pb2'
  # @@protoc_insertion_point(class_scope:RpcAddRsp)
  ))
_sym_db.RegisterMessage(RpcAddRsp)


# @@protoc_insertion_point(module_scope)
