name: Deploy to prd

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: "Optional Commit SHA for deployment"
        required: false

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          python -m pip install requests
          python -m pip install fsbot

      - name: Get last workflow_dispatch commit on main
        id: last_dispatch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "当前 commit: ${{ github.sha }}"
          previous_sha=$(gh api \
            repos/${{ github.repository }}/actions/workflows/deploy.yml/runs \
            --paginate \
            -q '.workflow_runs[] | select(.event == "workflow_dispatch" and .status == "completed" and .conclusion == "success" and .head_branch == "main") | .head_sha' \
            | grep -v "${{ github.sha }}" \
            | head -n 1)

          echo "PREV_COMMIT_SHA=$previous_sha" >> $GITHUB_ENV
          echo "Last deploy SHA: $previous_sha"

      - name: Get commit log since last deploy
        id: gitlog
        run: |
          if [ -n "$PREV_COMMIT_SHA" ]; then
            echo "Commits since last deploy:"
            git log --pretty=format:"- %s (%an)" $PREV_COMMIT_SHA..${{ github.sha }} > commit_diff.txt
          else
            echo "No previous manual deploy found. Showing all commits." > commit_diff.txt
            git log --pretty=format:"- %s (%an)" > commit_diff.txt
          fi

      - name: set commit info
        run: |
          echo pr_user=${{ github.actor }} >> $GITHUB_ENV
          echo pr_type="release" >> $GITHUB_ENV

      - name: call lark webhook
        run: |
          python .github/workflows/pr_message.py
